import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from './prisma.service';
import { DevelopmentPaymentProvider, PaymentProvider } from './payment.provider';
@Injectable()
export class PaymentService {
  private readonly provider: PaymentProvider = new DevelopmentPaymentProvider();
  constructor(private readonly prisma: PrismaService) {}
  async create(userId: string, orderId: string) { const order = await this.prisma.order.findFirst({ where: { id: orderId, userId }, include: { payments: true } }); if (!order) throw new NotFoundException('Order not found'); if (order.status === 'PAID') throw new BadRequestException('Order already paid'); const existing = order.payments.find(p => p.status === 'CREATED'); if (existing) return existing; return this.prisma.payment.create({ data: { orderId, amount: order.total, provider: 'development', idempotencyKey: `order:${orderId}` } }); }
  async confirm(userId: string, paymentId: string) { const payment = await this.prisma.payment.findFirst({ where: { id: paymentId, order: { userId } }, include: { order: { include: { items: true } } } }); if (!payment) throw new NotFoundException('Payment not found'); if (payment.status === 'SUCCEEDED') return payment; const result = await this.provider.createPayment({ orderId: payment.orderId, amount: Number(payment.amount), currency: payment.order.currency, idempotencyKey: payment.idempotencyKey }); if (result.status !== 'SUCCEEDED') throw new BadRequestException('Payment failed'); return this.succeed(payment.id, result.transactionId); }
  async webhook(paymentId: string, eventId: string) { const payment = await this.prisma.payment.findUnique({ where: { id: paymentId }, include: { order: { include: { items: true } } } }); if (!payment) throw new NotFoundException('Payment not found'); if (payment.status === 'SUCCEEDED') return { duplicate: true, payment }; return { duplicate: false, payment: await this.succeed(payment.id, `webhook_${eventId}`) }; }
  private async succeed(paymentId: string, transactionId: string) { return this.prisma.$transaction(async tx => { const payment = await tx.payment.update({ where: { id: paymentId }, data: { status: 'SUCCEEDED', transactionId }, include: { order: { include: { items: true } } } }); await tx.order.update({ where: { id: payment.orderId }, data: { status: 'PAID', paidAt: new Date() } }); for (const item of payment.order.items) await tx.downloadPermission.upsert({ where: { userId_productId: { userId: payment.order.userId, productId: item.productId } }, update: {}, create: { userId: payment.order.userId, productId: item.productId, orderId: payment.orderId } }); return payment; }); }
}
